WITH TBL AS (
    SELECT DISTINCT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, S.USER_ID
    FROM USER_INFO I JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
    AND I.JOINED LIKE '2021%'
)

SELECT YEAR, MONTH, COUNT(USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM TBL
GROUP BY MONTH
ORDER BY YEAR, MONTH