WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT CHILD.ID, CHILD.PARENT_ID, PARENT.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA CHILD INNER JOIN CTE PARENT
    ON CHILD.PARENT_ID = PARENT.ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM CTE
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM CTE
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION