WITH TBL AS (
    SELECT H.HISTORY_ID, C.DAILY_FEE, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DIFF,
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 7 THEN 0
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE = '7일 이상')
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE = '30일 이상')
        ELSE (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE = '90일 이상')
    END AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, TRUNCATE(DAILY_FEE * DIFF * (100 - DISCOUNT_RATE) / 100, -1) AS FEE
FROM TBL
ORDER BY FEE DESC, HISTORY_ID DESC