SELECT E.EMP_NO, E.EMP_NAME,
CASE
    WHEN AVG(G.SCORE) >= 96 THEN 'S'
    WHEN AVG(G.SCORE) >= 90 THEN 'A'
    WHEN AVG(G.SCORE) >= 80 THEN 'B'
    ELSE 'C'
END AS GRADE,
CASE
    WHEN AVG(G.SCORE) >= 96 THEN SAL * 20 / 100
    WHEN AVG(G.SCORE) >= 90 THEN SAL * 15 / 100
    WHEN AVG(G.SCORE) >= 80 THEN SAL * 10 / 100
    ELSE 0
END AS BONUS
FROM HR_EMPLOYEES E JOIN HR_DEPARTMENT D
ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE G
ON G.EMP_NO = E.EMP_NO
GROUP BY E.EMP_NO
ORDER BY EMP_NO