select CHILD.ID as ID, CHILD.GENOTYPE as GENOTYPE, PARENT.GENOTYPE as PARENT_GENOTYPE
from ECOLI_DATA as PARENT 
join ECOLI_DATA as CHILD
on PARENT.ID = CHILD.PARENT_ID
WHERE (PARENT.GENOTYPE & CHILD.GENOTYPE) = PARENT.GENOTYPE;