select 
        YEAR(DIFFERENTIATION_DATE) as YEAR,
        max(SIZE_OF_COLONY) over(PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY as YEAR_DEV,
        id
from ECOLI_DATA
order by YEAR, YEAR_DEV;