WITH CODE_SUM AS (
    SELECT (
        SELECT SUM(CODE) AS SUM_CODE 
        FROM SKILLCODES
        WHERE NAME = 'C#'
    ) AS C_SHARP,
    (
        SELECT SUM(CODE) AS SUM_CODE 
        FROM SKILLCODES
        WHERE CATEGORY = 'Front End'
    ) AS FRONT_END,
    (
        SELECT CODE 
        FROM SKILLCODES 
        WHERE NAME = 'Python'
    ) AS PYTHON
), TBL AS (
    SELECT
    CASE
    WHEN SKILL_CODE & (SELECT PYTHON FROM CODE_SUM) != 0
    AND SKILL_CODE & (SELECT FRONT_END FROM CODE_SUM) != 0 THEN 'A'
    WHEN SKILL_CODE & (SELECT C_SHARP FROM CODE_SUM) != 0 THEN 'B'
    WHEN SKILL_CODE & (SELECT FRONT_END FROM CODE_SUM) != 0 THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
    FROM DEVELOPERS
)

SELECT GRADE, ID, EMAIL
FROM TBL
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID

